from . import test_reception
from . import test_pos_stock
from . import test_stock_deficit
from . import test_instalacion
from . import test_security
from . import test_access
from . import test_actualizacion
from . import test_backup
from . import test_mantenimiento
from . import test_actualizador
from . import test_pos_receipt
from . import test_catalog_import
from . import test_bouquet
from . import test_event
from . import test_event_pos
from . import test_consumption
from . import test_escpos
from . import test_res_company
from . import test_stock_alert
from . import test_product_panel
from . import test_product_category
from . import test_stock_ledger
from . import test_menus
from . import test_pos_category
